---
# To be used with `make env`
name: complexity
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
    - bubblewrap=0.8.0
    - python=3.10
    - contourpy=1.3.1
    - cycler=0.12.1
    - exceptiongroup=1.2.2
    - filelock=3.17.0
    - fonttools=4.56.0
    - iniconfig=2.0.0
    - joblib=1.4.2
    - kiwisolver=1.4.8
    - matplotlib=3.10.1
    - numpy=2.2.3
    - packaging=24.2
    - pillow=11.1.0
    - pluggy=1.5.0
    - psutil=7.0.0
    - pyparsing=3.2.1
    - pytest=8.3.5
    - python-dateutil=2.9.0.post0
    - scikit-learn=1.6.1
    - scipy=1.15.2
    - six=1.17.0
    - threadpoolctl=3.5.0
    - tomli=2.2.1
